### ISSUE TITLE
Might be a good idea to add windows support

### ISSUE THREAD

**Issue by inunotaisho26** [substack/node-mkdirp#143]
I have to know how to use Windows in case my job requires it, so I would like a rimraf windows version of this package made available. Otherwise I get this error:

`'mkdirp' is not recognized as an internal or external command, operable program or batch file.`

Screws with my projects I have written on Mac and Linux.

**Comment by etrupja** [comment]
@inunotaisho26  On windows make sure that you install the package mkdirp:
`npm i -g mkdir`
You can check more here: https://www.npmjs.com/package/mkdir
