### ISSUE TITLE
curious about why a simple bash process is not used

### ISSUE THREAD

**Issue by ORESoftware** [substack/node-mkdirp#146]
I have been wondering for awhile, why not just use:

```js
const k = cp.spawn('bash');
k.end(`mkdir -p ${pth};\n`);
```

is it primarily to keep things x-platform?

**Comment by ljharb** [comment]
yes

**Comment by ccoenen** [comment]
This has been answered. It would be nice if @ORESoftware would close the ticket.

**Comment by ORESoftware** [comment]
closing as answered
