### ISSUE TITLE
看了一下，感觉逻辑比较复杂。于是重新写了一下。不知道这样行不行

### ISSUE THREAD

**Issue by mrxu0** [substack/node-mkdirp#150]
```
let fs = require('fs')
var path = require('path');

var allPaht = null;
var fun = null
function mkdir(pathh, callback) {
  if (!allPaht) allPaht = path.resolve(pathh)
  if (!fun) fun = callback
  let resPath = path.resolve(pathh)
  fs.mkdir(resPath, function(err){
    if(!err) {
      if (allPaht == resPath) fun(null)
      return 
    } 
    switch (err.code) {
      case 'ENOENT':
        mkdir(path.dirname(resPath))
        mkdir(pathh)
        break;
      default:
        fun('目录已存在')
        break;
    }
  })
}
```

**Comment by mrxu0** [comment]
我尝试过，回调是可以被调用的。

**Comment by AnsonYeung** [comment]
Well, what about when it encounter an error

**Comment by AnsonYeung** [comment]
Your code also doesn't appear to have all features as the original

And you make some unnecessary global variable

**Comment by mrxu0** [comment]
哦哦，我尝试了你说的这种情况是没问题的。你确定你试过了么？

**Comment by AnsonYeung** [comment]
I suggest you to use fs-extra if you knows es6. [A website that introduce es6](https://es6-features.org)
It uses promise which really simplifies thing with the introduction of es8 `async`/`await` keyword.
You can use the two line code with the new feature. After some modification to the mkdir function to return a promise, the correct code can now be
```js
await mkdir(path.dirname(resPath));
await mkdir(pathh);
```
which is indeed awesome.

**Comment by AnsonYeung** [comment]
fs-extra can be used as a drop-in replacement to the built-in fs module.
that is

Add fs-extra as a dependancy of your directory (or package if you like, idk how to call that).
```bash
npm i fs-extra
```

example.js
```js
const fs = require("fs-extra");
```

**Comment by mrxu0** [comment]
感谢你的用心回答，其中你说的全局变量和面条代码我在书写的时候是有意识到的。我本意只是看了你的代码萌生出了一个我认为比较不错的点子跟你分享一下。也没有考虑太多的执行环境和创建文件方式等等，这是我的疏忽，再次感谢你的用心回答。
