### ISSUE TITLE
Continuous Maintenance

### ISSUE THREAD

**Issue by gfx** [substack/node-mkdirp#158]
Hello.

This module is widely used in NodeJS ecosystem but it seems not to be maintained actively, even though it is stable enough for years. However, there seem lots of issues and pull requests, so I think there are rooms to be improved.

So I propose that this module should be moved to some organization to maintain it continuously. What do you think of it?

**Comment by VRMartin** [comment]
Or perhaps see npm make-dir and use it

**Comment by TheGrandmother** [comment]
Or just use `fs.mkdir("some/random/path", {recursive: true})`
And it has the same effect.

**Comment by gfx** [comment]
@TheGrandmother 

Nice suggestsion!

https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback

Its history sais `recursive` option was added in v10.12.0, so we no longer use a third-party library for `mkdir -p`.

Thanks.
