### ISSUE TITLE
Admin Issue

### ISSUE THREAD

**Issue by afreeland** [substack/node-mkdirp#85]
We have been using mkdirp for a little while now and were setting up a new users environment and came across an issue we had not before:
`
Error: UNKNOWN, open '\\somepath\path\filename.txt'
`

After some further investigation we realized that `mkdirp` module creates a `.bin` folder with a command script in it.

Apparently, this requires the user logged in to be elevated to admin to work appropriately...sure would be great if instead of  getting `Error: UNKNOWN, open` error, to of received something that might of hinted us to the privilege escalation sooner...or have some docs that call that out.

I would love to see this get added and I wanted to make sure to post this in case anyone ran across the  issue.

**Comment by clounie** [comment]
You can tell npm not to create symlinks for binaries (i.e. it doesn't add anything to the `.bin` folder) with the `--no-bin-links` option. Ex: `npm install mkdirp --save --no-bin-links`

More info:
 * [Using `.bin`](http://firstdoit.com/npm-scripts/#npmscriptsunderstandbin)
 * [npm docs](https://docs.npmjs.com/cli/install) (you'll have to `Ctrl+F` for it)
