### ISSUE TITLE
Add Promise support

### ISSUE THREAD

**Issue by astorije** [substack/node-mkdirp#86]
Would you be open to support [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)?

Essentially, [your first example in the README](https://github.com/substack/node-mkdirp#powjs) would become:

```js
var mkdirp = require('mkdirp');
var creation = mkdirp('/tmp/foo/bar/baz');
// [...]

creation
  .then(function () { console.log('pow!'); })
  .catch(console.error);
```

In terms of implementation, it could work as follows: if `cb` (as in `mkdirp(dir, opts, cb)`) is provided and is a `function`, it returns nothing and executes `cb` like it does today; otherwise, it returns a Promise.

How does that sound?

**Comment by jprichardson** [comment]
Why not just use one of the many Promise libraries that will promisify a function? e.g. https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function

**Comment by astorije** [comment]
Because doing so is just a temporary/hackish solution until promise support is enabled, or to overcome libraries that purposely refuse to return promises :-)

Native support is always better for client integration as users do not have to worry about wrapping the functions. Not to forget that [Promises/A+](https://promisesaplus.com/) are a standard where callbacks aren't. Maybe we should have promise-based-only libraries and callback libraries that will callbackify functions instead :P

That said, I am willing to send a PR for this, I am merely asking for authorization before doing so myself!

**Comment by schnittstabil** [comment]
`promisify` is [rather complicated](https://github.com/petkaantonov/bluebird/blob/master/src/promisify.js). Also, most implementations I am aware of slice their arguments (e.g. `[].slice.call(arguments)`), which prevents optimizations in JavaScript engines.

**Comment by TrySound** [comment]
This uses in [del](https://github.com/sindresorhus/del)
[pinkie-promise](https://github.com/floatdrop/pinkie-promise)

**Comment by yoshuawuyts** [comment]
-1, it's super easy to promisify a function yourself. We shouldn't be making libraries heavier than they strictly need to be, especially if they're as widely used as `mkdirp`.

**Comment by TrySound** [comment]
Promises supports since node 0.12.

**Comment by klimashkin** [comment]
Today all modules can (and should) use Promise.
If user have no Promise in his environment (and he knows it, for example node <=0.10), he just uses Promise polyfill

**Comment by TrySound** [comment]
@klimashkin :+1:

**Comment by substack** [comment]
I don't like promises.

**Comment by klimashkin** [comment]
@substack,  You should have said "I don't like hollow promises" :)

**Comment by astorije** [comment]
Lol, best argumentation ever. Thanks for closing this!

Whether you like it or not, promises are here. Refusing to use them is like sticking to using Flash for videos while HTML5 has native support for it.

@yoshuawuyts, -1 to using promisify. Libraries should return promises as it is the standard, and they are needed. It's not making the library heavier, as it's a natural evolution of the language. Similarly, browser APIs are slowly but surely moving towards native promise support.

**Comment by mikermcneil** [comment]
> I don't like promises.
 :+1:

**Comment by azer** [comment]
there is already a module adding promise support to mkdirp; https://www.npmjs.com/package/mkdirp-promise.

![](https://cldup.com/xaE8NjCQEw.gif)

**Comment by mattdesl** [comment]
> Today all modules can (and should) use Promise.

This is not always a good idea. Expecting `Promise` introduces a peer-dependency on polyfills for consumers in legacy environments, which adds a deal of bloat/opinion/complexity to an otherwise small and simple module. This particularly affects frontend developers using npm.

There is also something to be said about stability and a frozen API. With 14 million downloads a month and countless dependents, it is better just to leave a module as-is rather than overturn its API for some slight syntax sugar.

**Comment by ioncreature** [comment]
@klimashkin 
Fully agree with @substack. Node uses its own style.

**Comment by TrySound** [comment]
@ioncreature Promises is not style. It's part of language.

**Comment by nicholasf** [comment]
Isn't this a very old topic that was resolved a certain way in 2011?

**Comment by Ohar** [comment]
>it is better just to leave a module as-is rather than overturn its API

@mattdesl No. Its is not.
Better is to release new major module version.

**Comment by popomore** [comment]
Maybe you can use  https://github.com/node-modules/mz-modules

**Comment by mattbrunetti** [comment]
@substack 

> I don't like promises.

Do you still feel that way about promises?

You've already shared so much with us that it's difficult to ask this, but would you share with us why we shouldn't like promises?

**Comment by TrySound** [comment]
@gorilla-devs Use this package. https://www.npmjs.com/package/make-dir
