### ISSUE TITLE
Add curly brace expansion:

### ISSUE THREAD

**Issue by jamestalmage** [substack/node-mkdirp#95]
Allow for:

```js
mkdirp('/build/{js,css,img}');
```

I can work up a PR if people think it's a good idea.

**Comment by dacodekid** [comment]
I created one as a separate package [here](https://github.com/dacodekid/node-folder) and found another [here](https://www.npmjs.com/package/mkdirps-brackets)- but love to see this on the core package itself.

**Comment by schnittstabil** [comment]
Sounds interesting; How would creating the single directory `/build/{js,css,img}` be handled?

**Comment by jamestalmage** [comment]
> what is the advantage over ... `brace-expansion`

Well, **if** `mkdirp` supports an array as the first argument, then none really. I wasn't aware that it did (I certainly don't see it in the docs).

That may actually represent a better choice (allowing an array, and telling people to find a brace-expansion solution if they need it).

**Comment by jamestalmage** [comment]
> How would creating the single directory `/build/{js,css,img}` be handled

Good point. Another argument for just accepting an array.

**Comment by dacodekid** [comment]
Does ```mkdirp``` supports array?  While try I'm getting ```TypeError: Path must be a string. Received [ 'build/src' ]``` error.  But since I no longer have problem passing a single folder to ```brace-expansion```, now all I have to do is pass the array through a ```for``` loop.  If array been supported with ```mkdirp``` I no longer need my package.

@schnittstabil  Thx :+1:

**Comment by schnittstabil** [comment]
> Does mkdirp supports array?

Oh, I see, it does not :-(

**Comment by schnittstabil** [comment]
Sadly `mkdirp` also doesn't support Promises #86:
```js
var tasks = expand('/build/{js,css,img}').map(path => mkdirp(path));
Promise.all(tasks).then(() => {       // <- does not work
  // directories created
});
```

**Comment by jamestalmage** [comment]
After actually taking the time to look at the project, it is becoming apparent the intention is to keep the dependency list small. Brace expansion, array support, and promises would all incur additional dependencies. Better to write a wrapper and deploy it to npm separately (as @dacodekid has already done).
