### ISSUE TITLE
Make mkdirp compatibile with strict mode

### ISSUE THREAD

**Issue by lukeapage** [substack/node-mkdirp#98]
Strict mode does not allow octal literals.

This for instance stops mkdirp from being used with rollup - https://github.com/rollup/rollup/issues/361

**Comment by jprichardson** [comment]
Update your version? https://github.com/substack/node-mkdirp/commit/48e67fce39f1a5f2aba6196301b7be6d4545d6cf

**Comment by lukeapage** [comment]
ok.. was a sub dependency.. will raise the issue with fs-jetpack
